export const formulaSeed = [
  {
    id: 0,
    formulaName: 'commonHeadphoneLevelAndCharge',
    description: 'commonHeadphoneLevelAndCharge',
    formulaArray: [
      {
        level: 0,
        levelUpCostBlb: 1,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 60,
        boostingCostBlb: 6,
        boostingCostLbl: 0,
        chargingCostBlb: 0.3,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 5,
      },
      {
        level: 1,
        levelUpCostBlb: 2,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 120,
        boostingCostBlb: 12,
        boostingCostLbl: 0,
        chargingCostBlb: 0.31,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 10,
      },
      {
        level: 2,
        levelUpCostBlb: 3,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 180,
        boostingCostBlb: 18,
        boostingCostLbl: 0,
        chargingCostBlb: 0.32,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 15,
      },
      {
        level: 3,
        levelUpCostBlb: 4,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 240,
        boostingCostBlb: 24,
        boostingCostLbl: 0,
        chargingCostBlb: 0.33,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 20,
      },
      {
        level: 4,
        levelUpCostBlb: 10,
        levelUpCostLbl: 10,
        levelUpRequiredMinutes: 300,
        boostingCostBlb: 30,
        boostingCostLbl: 0,
        chargingCostBlb: 0.34,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 25,
      },
      {
        level: 5,
        levelUpCostBlb: 6,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 360,
        boostingCostBlb: 36,
        boostingCostLbl: 0,
        chargingCostBlb: 0.36,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 30,
      },
      {
        level: 6,
        levelUpCostBlb: 7,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 420,
        boostingCostBlb: 42,
        boostingCostLbl: 0,
        chargingCostBlb: 0.37,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 35,
      },
      {
        level: 7,
        levelUpCostBlb: 8,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 480,
        boostingCostBlb: 48,
        boostingCostLbl: 0,
        chargingCostBlb: 0.38,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 40,
      },
      {
        level: 8,
        levelUpCostBlb: 9,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 540,
        boostingCostBlb: 54,
        boostingCostLbl: 0,
        chargingCostBlb: 0.4,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 45,
      },
      {
        level: 9,
        levelUpCostBlb: 30,
        levelUpCostLbl: 30,
        levelUpRequiredMinutes: 600,
        boostingCostBlb: 60,
        boostingCostLbl: 0,
        chargingCostBlb: 0.41,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 50,
      },
      {
        level: 10,
        levelUpCostBlb: 11,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 660,
        boostingCostBlb: 66,
        boostingCostLbl: 0,
        chargingCostBlb: 0.43,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 60,
      },
      {
        level: 11,
        levelUpCostBlb: 12,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 720,
        boostingCostBlb: 72,
        boostingCostLbl: 0,
        chargingCostBlb: 0.44,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 70,
      },
      {
        level: 12,
        levelUpCostBlb: 13,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 780,
        boostingCostBlb: 78,
        boostingCostLbl: 0,
        chargingCostBlb: 0.46,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 80,
      },
      {
        level: 13,
        levelUpCostBlb: 14,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 840,
        boostingCostBlb: 84,
        boostingCostLbl: 0,
        chargingCostBlb: 0.48,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 90,
      },
      {
        level: 14,
        levelUpCostBlb: 15,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 900,
        boostingCostBlb: 90,
        boostingCostLbl: 0,
        chargingCostBlb: 0.5,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 100,
      },
      {
        level: 15,
        levelUpCostBlb: 16,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 960,
        boostingCostBlb: 96,
        boostingCostLbl: 0,
        chargingCostBlb: 0.51,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 110,
      },
      {
        level: 16,
        levelUpCostBlb: 17,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1020,
        boostingCostBlb: 102,
        boostingCostLbl: 0,
        chargingCostBlb: 0.54,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 120,
      },
      {
        level: 17,
        levelUpCostBlb: 18,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1080,
        boostingCostBlb: 108,
        boostingCostLbl: 0,
        chargingCostBlb: 0.55,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 130,
      },
      {
        level: 18,
        levelUpCostBlb: 19,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1140,
        boostingCostBlb: 114,
        boostingCostLbl: 0,
        chargingCostBlb: 0.57,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 140,
      },
      {
        level: 19,
        levelUpCostBlb: 60,
        levelUpCostLbl: 60,
        levelUpRequiredMinutes: 1200,
        boostingCostBlb: 120,
        boostingCostLbl: 0,
        chargingCostBlb: 0.6,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 150,
      },
      {
        level: 20,
        levelUpCostBlb: 21,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1260,
        boostingCostBlb: 126,
        boostingCostLbl: 0,
        chargingCostBlb: 0.62,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 160,
      },
      {
        level: 21,
        levelUpCostBlb: 22,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1320,
        boostingCostBlb: 132,
        boostingCostLbl: 0,
        chargingCostBlb: 0.64,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 170,
      },
      {
        level: 22,
        levelUpCostBlb: 23,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1380,
        boostingCostBlb: 138,
        boostingCostLbl: 0,
        chargingCostBlb: 0.67,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 180,
      },
      {
        level: 23,
        levelUpCostBlb: 24,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1440,
        boostingCostBlb: 144,
        boostingCostLbl: 0,
        chargingCostBlb: 0.69,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 195,
      },
      {
        level: 24,
        levelUpCostBlb: 25,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1500,
        boostingCostBlb: 150,
        boostingCostLbl: 0,
        chargingCostBlb: 0.72,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 210,
      },
      {
        level: 25,
        levelUpCostBlb: 26,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1560,
        boostingCostBlb: 156,
        boostingCostLbl: 0,
        chargingCostBlb: 0.75,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 225,
      },
      {
        level: 26,
        levelUpCostBlb: 27,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1620,
        boostingCostBlb: 162,
        boostingCostLbl: 0,
        chargingCostBlb: 0.78,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 240,
      },
      {
        level: 27,
        levelUpCostBlb: 28,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1680,
        boostingCostBlb: 168,
        boostingCostLbl: 0,
        chargingCostBlb: 0.81,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 255,
      },
      {
        level: 28,
        levelUpCostBlb: 29,
        levelUpCostLbl: 29,
        levelUpRequiredMinutes: 1740,
        boostingCostBlb: 174,
        boostingCostLbl: 0,
        chargingCostBlb: 0.83,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 270,
      },
      {
        level: 29,
        levelUpCostBlb: 100,
        levelUpCostLbl: 100,
        levelUpRequiredMinutes: 1800,
        boostingCostBlb: 180,
        boostingCostLbl: 0,
        chargingCostBlb: 0.85,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 285,
      },
      {
        level: 30,
        levelUpCostBlb: 999999999,
        levelUpCostLbl: 999999999,
        levelUpRequiredMinutes: 999999999,
        boostingCostBlb: 999999999,
        boostingCostLbl: 999999999,
        chargingCostBlb: 0.9,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 300,
      },
    ],
  },
  {
    id: 1,
    formulaName: 'uncommonHeadphoneLevelAndCharge',
    description: 'uncommonHeadphoneLevelAndCharge',
    formulaArray: [
      {
        level: 0,
        levelUpCostBlb: 2,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 120,
        boostingCostBlb: 12,
        boostingCostLbl: 0,
        chargingCostBlb: 0.4,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 5,
      },
      {
        level: 1,
        levelUpCostBlb: 4,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 240,
        boostingCostBlb: 24,
        boostingCostLbl: 0,
        chargingCostBlb: 0.41,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 10,
      },
      {
        level: 2,
        levelUpCostBlb: 6,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 360,
        boostingCostBlb: 36,
        boostingCostLbl: 0,
        chargingCostBlb: 0.42,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 15,
      },
      {
        level: 3,
        levelUpCostBlb: 8,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 480,
        boostingCostBlb: 48,
        boostingCostLbl: 0,
        chargingCostBlb: 0.43,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 20,
      },
      {
        level: 4,
        levelUpCostBlb: 20,
        levelUpCostLbl: 20,
        levelUpRequiredMinutes: 600,
        boostingCostBlb: 60,
        boostingCostLbl: 0,
        chargingCostBlb: 0.44,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 25,
      },
      {
        level: 5,
        levelUpCostBlb: 12,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 720,
        boostingCostBlb: 72,
        boostingCostLbl: 0,
        chargingCostBlb: 0.47,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 30,
      },
      {
        level: 6,
        levelUpCostBlb: 14,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 840,
        boostingCostBlb: 84,
        boostingCostLbl: 0,
        chargingCostBlb: 0.49,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 35,
      },
      {
        level: 7,
        levelUpCostBlb: 16,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 960,
        boostingCostBlb: 96,
        boostingCostLbl: 0,
        chargingCostBlb: 0.51,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 40,
      },
      {
        level: 8,
        levelUpCostBlb: 18,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1080,
        boostingCostBlb: 108,
        boostingCostLbl: 0,
        chargingCostBlb: 0.53,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 45,
      },
      {
        level: 9,
        levelUpCostBlb: 60,
        levelUpCostLbl: 60,
        levelUpRequiredMinutes: 1200,
        boostingCostBlb: 120,
        boostingCostLbl: 0,
        chargingCostBlb: 0.55,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 50,
      },
      {
        level: 10,
        levelUpCostBlb: 22,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1320,
        boostingCostBlb: 132,
        boostingCostLbl: 0,
        chargingCostBlb: 0.57,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 60,
      },
      {
        level: 11,
        levelUpCostBlb: 24,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1440,
        boostingCostBlb: 144,
        boostingCostLbl: 0,
        chargingCostBlb: 0.6,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 70,
      },
      {
        level: 12,
        levelUpCostBlb: 26,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1560,
        boostingCostBlb: 156,
        boostingCostLbl: 0,
        chargingCostBlb: 0.62,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 80,
      },
      {
        level: 13,
        levelUpCostBlb: 28,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1680,
        boostingCostBlb: 168,
        boostingCostLbl: 0,
        chargingCostBlb: 0.64,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 90,
      },
      {
        level: 14,
        levelUpCostBlb: 30,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1800,
        boostingCostBlb: 180,
        boostingCostLbl: 0,
        chargingCostBlb: 0.66,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 100,
      },
      {
        level: 15,
        levelUpCostBlb: 32,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1920,
        boostingCostBlb: 192,
        boostingCostLbl: 0,
        chargingCostBlb: 0.67,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 110,
      },
      {
        level: 16,
        levelUpCostBlb: 34,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 2040,
        boostingCostBlb: 204,
        boostingCostLbl: 0,
        chargingCostBlb: 0.69,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 120,
      },
      {
        level: 17,
        levelUpCostBlb: 36,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 2160,
        boostingCostBlb: 216,
        boostingCostLbl: 0,
        chargingCostBlb: 0.71,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 130,
      },
      {
        level: 18,
        levelUpCostBlb: 38,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 2280,
        boostingCostBlb: 228,
        boostingCostLbl: 0,
        chargingCostBlb: 0.73,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 140,
      },
      {
        level: 19,
        levelUpCostBlb: 120,
        levelUpCostLbl: 120,
        levelUpRequiredMinutes: 2400,
        boostingCostBlb: 240,
        boostingCostLbl: 0,
        chargingCostBlb: 0.75,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 150,
      },
      {
        level: 20,
        levelUpCostBlb: 42,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 2520,
        boostingCostBlb: 252,
        boostingCostLbl: 0,
        chargingCostBlb: 0.77,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 160,
      },
      {
        level: 21,
        levelUpCostBlb: 44,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 2640,
        boostingCostBlb: 264,
        boostingCostLbl: 0,
        chargingCostBlb: 0.79,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 170,
      },
      {
        level: 22,
        levelUpCostBlb: 46,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 2760,
        boostingCostBlb: 276,
        boostingCostLbl: 0,
        chargingCostBlb: 0.82,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 180,
      },
      {
        level: 23,
        levelUpCostBlb: 48,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 2880,
        boostingCostBlb: 288,
        boostingCostLbl: 0,
        chargingCostBlb: 0.84,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 195,
      },
      {
        level: 24,
        levelUpCostBlb: 50,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 3000,
        boostingCostBlb: 300,
        boostingCostLbl: 0,
        chargingCostBlb: 0.87,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 210,
      },
      {
        level: 25,
        levelUpCostBlb: 52,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 3120,
        boostingCostBlb: 312,
        boostingCostLbl: 0,
        chargingCostBlb: 0.9,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 225,
      },
      {
        level: 26,
        levelUpCostBlb: 54,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 3240,
        boostingCostBlb: 324,
        boostingCostLbl: 0,
        chargingCostBlb: 0.93,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 240,
      },
      {
        level: 27,
        levelUpCostBlb: 56,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 3360,
        boostingCostBlb: 336,
        boostingCostLbl: 0,
        chargingCostBlb: 0.96,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 255,
      },
      {
        level: 28,
        levelUpCostBlb: 58,
        levelUpCostLbl: 58,
        levelUpRequiredMinutes: 3480,
        boostingCostBlb: 348,
        boostingCostLbl: 0,
        chargingCostBlb: 0.98,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 270,
      },
      {
        level: 29,
        levelUpCostBlb: 200,
        levelUpCostLbl: 200,
        levelUpRequiredMinutes: 3600,
        boostingCostBlb: 360,
        boostingCostLbl: 0,
        chargingCostBlb: 1,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 285,
      },
      {
        level: 30,
        levelUpCostBlb: 999999999,
        levelUpCostLbl: 999999999,
        levelUpRequiredMinutes: 999999999,
        boostingCostBlb: 999999999,
        boostingCostLbl: 999999999,
        chargingCostBlb: 1.1,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 300,
      },
    ],
  },
  {
    id: 2,
    formulaName: 'rareHeadphoneLevelAndCharge',
    description: 'rareHeadphoneLevelAndCharge',
    formulaArray: [
      {
        level: 0,
        levelUpCostBlb: 4,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 240,
        boostingCostBlb: 24,
        boostingCostLbl: 0,
        chargingCostBlb: 0.43,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 5,
      },
      {
        level: 1,
        levelUpCostBlb: 8,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 480,
        boostingCostBlb: 48,
        boostingCostLbl: 0,
        chargingCostBlb: 0.46,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 10,
      },
      {
        level: 2,
        levelUpCostBlb: 12,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 720,
        boostingCostBlb: 72,
        boostingCostLbl: 0,
        chargingCostBlb: 0.49,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 15,
      },
      {
        level: 3,
        levelUpCostBlb: 16,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 960,
        boostingCostBlb: 96,
        boostingCostLbl: 0,
        chargingCostBlb: 0.52,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 20,
      },
      {
        level: 4,
        levelUpCostBlb: 40,
        levelUpCostLbl: 40,
        levelUpRequiredMinutes: 1200,
        boostingCostBlb: 120,
        boostingCostLbl: 0,
        chargingCostBlb: 0.55,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 25,
      },
      {
        level: 5,
        levelUpCostBlb: 24,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1440,
        boostingCostBlb: 144,
        boostingCostLbl: 0,
        chargingCostBlb: 0.58,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 30,
      },
      {
        level: 6,
        levelUpCostBlb: 28,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1680,
        boostingCostBlb: 168,
        boostingCostLbl: 0,
        chargingCostBlb: 0.61,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 35,
      },
      {
        level: 7,
        levelUpCostBlb: 32,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1920,
        boostingCostBlb: 192,
        boostingCostLbl: 0,
        chargingCostBlb: 0.64,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 40,
      },
      {
        level: 8,
        levelUpCostBlb: 36,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 2160,
        boostingCostBlb: 216,
        boostingCostLbl: 0,
        chargingCostBlb: 0.67,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 45,
      },
      {
        level: 9,
        levelUpCostBlb: 120,
        levelUpCostLbl: 120,
        levelUpRequiredMinutes: 2400,
        boostingCostBlb: 240,
        boostingCostLbl: 0,
        chargingCostBlb: 0.69,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 50,
      },
      {
        level: 10,
        levelUpCostBlb: 44,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 2640,
        boostingCostBlb: 264,
        boostingCostLbl: 0,
        chargingCostBlb: 0.72,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 60,
      },
      {
        level: 11,
        levelUpCostBlb: 48,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 2880,
        boostingCostBlb: 288,
        boostingCostLbl: 0,
        chargingCostBlb: 0.75,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 70,
      },
      {
        level: 12,
        levelUpCostBlb: 52,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 3120,
        boostingCostBlb: 312,
        boostingCostLbl: 0,
        chargingCostBlb: 0.77,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 80,
      },
      {
        level: 13,
        levelUpCostBlb: 56,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 3360,
        boostingCostBlb: 336,
        boostingCostLbl: 0,
        chargingCostBlb: 0.8,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 90,
      },
      {
        level: 14,
        levelUpCostBlb: 60,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 3600,
        boostingCostBlb: 360,
        boostingCostLbl: 0,
        chargingCostBlb: 0.83,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 100,
      },
      {
        level: 15,
        levelUpCostBlb: 64,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 3840,
        boostingCostBlb: 384,
        boostingCostLbl: 0,
        chargingCostBlb: 0.86,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 110,
      },
      {
        level: 16,
        levelUpCostBlb: 68,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 4080,
        boostingCostBlb: 408,
        boostingCostLbl: 0,
        chargingCostBlb: 0.89,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 120,
      },
      {
        level: 17,
        levelUpCostBlb: 72,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 4320,
        boostingCostBlb: 432,
        boostingCostLbl: 0,
        chargingCostBlb: 0.92,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 130,
      },
      {
        level: 18,
        levelUpCostBlb: 76,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 4560,
        boostingCostBlb: 456,
        boostingCostLbl: 0,
        chargingCostBlb: 0.95,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 140,
      },
      {
        level: 19,
        levelUpCostBlb: 240,
        levelUpCostLbl: 240,
        levelUpRequiredMinutes: 4800,
        boostingCostBlb: 480,
        boostingCostLbl: 0,
        chargingCostBlb: 0.98,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 150,
      },
      {
        level: 20,
        levelUpCostBlb: 84,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 5040,
        boostingCostBlb: 504,
        boostingCostLbl: 0,
        chargingCostBlb: 1.01,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 160,
      },
      {
        level: 21,
        levelUpCostBlb: 88,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 5280,
        boostingCostBlb: 528,
        boostingCostLbl: 0,
        chargingCostBlb: 1.04,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 170,
      },
      {
        level: 22,
        levelUpCostBlb: 92,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 5520,
        boostingCostBlb: 552,
        boostingCostLbl: 0,
        chargingCostBlb: 1.07,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 180,
      },
      {
        level: 23,
        levelUpCostBlb: 96,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 5760,
        boostingCostBlb: 576,
        boostingCostLbl: 0,
        chargingCostBlb: 1.1,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 195,
      },
      {
        level: 24,
        levelUpCostBlb: 100,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 6000,
        boostingCostBlb: 600,
        boostingCostLbl: 0,
        chargingCostBlb: 1.13,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 210,
      },
      {
        level: 25,
        levelUpCostBlb: 104,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 6240,
        boostingCostBlb: 624,
        boostingCostLbl: 0,
        chargingCostBlb: 1.16,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 225,
      },
      {
        level: 26,
        levelUpCostBlb: 108,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 6480,
        boostingCostBlb: 648,
        boostingCostLbl: 0,
        chargingCostBlb: 1.19,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 240,
      },
      {
        level: 27,
        levelUpCostBlb: 112,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 6720,
        boostingCostBlb: 672,
        boostingCostLbl: 0,
        chargingCostBlb: 1.22,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 255,
      },
      {
        level: 28,
        levelUpCostBlb: 116,
        levelUpCostLbl: 116,
        levelUpRequiredMinutes: 6960,
        boostingCostBlb: 696,
        boostingCostLbl: 0,
        chargingCostBlb: 1.25,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 270,
      },
      {
        level: 29,
        levelUpCostBlb: 400,
        levelUpCostLbl: 400,
        levelUpRequiredMinutes: 7200,
        boostingCostBlb: 720,
        boostingCostLbl: 0,
        chargingCostBlb: 1.28,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 285,
      },
      {
        level: 30,
        levelUpCostBlb: 999999999,
        levelUpCostLbl: 999999999,
        levelUpRequiredMinutes: 999999999,
        boostingCostBlb: 999999999,
        boostingCostLbl: 999999999,
        chargingCostBlb: 1.31,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 300,
      },
    ],
  },
  {
    id: 3,
    formulaName: 'epicHeadphoneLevelAndCharge',
    description: 'epicHeadphoneLevelAndCharge',
    formulaArray: [
      {
        level: 0,
        levelUpCostBlb: 8,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 480,
        boostingCostBlb: 48,
        boostingCostLbl: 0,
        chargingCostBlb: 0.6,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 5,
      },
      {
        level: 1,
        levelUpCostBlb: 16,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 960,
        boostingCostBlb: 96,
        boostingCostLbl: 0,
        chargingCostBlb: 0.62,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 10,
      },
      {
        level: 2,
        levelUpCostBlb: 24,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1440,
        boostingCostBlb: 144,
        boostingCostLbl: 0,
        chargingCostBlb: 0.64,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 15,
      },
      {
        level: 3,
        levelUpCostBlb: 32,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1920,
        boostingCostBlb: 192,
        boostingCostLbl: 0,
        chargingCostBlb: 0.66,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 20,
      },
      {
        level: 4,
        levelUpCostBlb: 80,
        levelUpCostLbl: 80,
        levelUpRequiredMinutes: 2400,
        boostingCostBlb: 240,
        boostingCostLbl: 0,
        chargingCostBlb: 0.68,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 25,
      },
      {
        level: 5,
        levelUpCostBlb: 48,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 2880,
        boostingCostBlb: 288,
        boostingCostLbl: 0,
        chargingCostBlb: 0.7,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 30,
      },
      {
        level: 6,
        levelUpCostBlb: 56,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 3360,
        boostingCostBlb: 336,
        boostingCostLbl: 0,
        chargingCostBlb: 0.72,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 35,
      },
      {
        level: 7,
        levelUpCostBlb: 64,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 3840,
        boostingCostBlb: 384,
        boostingCostLbl: 0,
        chargingCostBlb: 0.74,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 40,
      },
      {
        level: 8,
        levelUpCostBlb: 72,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 4320,
        boostingCostBlb: 432,
        boostingCostLbl: 0,
        chargingCostBlb: 0.76,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 45,
      },
      {
        level: 9,
        levelUpCostBlb: 240,
        levelUpCostLbl: 240,
        levelUpRequiredMinutes: 4800,
        boostingCostBlb: 480,
        boostingCostLbl: 0,
        chargingCostBlb: 0.78,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 50,
      },
      {
        level: 10,
        levelUpCostBlb: 88,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 5280,
        boostingCostBlb: 528,
        boostingCostLbl: 0,
        chargingCostBlb: 0.8,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 60,
      },
      {
        level: 11,
        levelUpCostBlb: 96,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 5760,
        boostingCostBlb: 576,
        boostingCostLbl: 0,
        chargingCostBlb: 0.82,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 70,
      },
      {
        level: 12,
        levelUpCostBlb: 104,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 6240,
        boostingCostBlb: 624,
        boostingCostLbl: 0,
        chargingCostBlb: 0.84,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 80,
      },
      {
        level: 13,
        levelUpCostBlb: 112,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 6720,
        boostingCostBlb: 672,
        boostingCostLbl: 0,
        chargingCostBlb: 0.86,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 90,
      },
      {
        level: 14,
        levelUpCostBlb: 120,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 7200,
        boostingCostBlb: 720,
        boostingCostLbl: 0,
        chargingCostBlb: 0.88,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 100,
      },
      {
        level: 15,
        levelUpCostBlb: 128,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 7680,
        boostingCostBlb: 768,
        boostingCostLbl: 0,
        chargingCostBlb: 0.9,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 110,
      },
      {
        level: 16,
        levelUpCostBlb: 136,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 8160,
        boostingCostBlb: 816,
        boostingCostLbl: 0,
        chargingCostBlb: 0.92,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 120,
      },
      {
        level: 17,
        levelUpCostBlb: 144,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 8640,
        boostingCostBlb: 864,
        boostingCostLbl: 0,
        chargingCostBlb: 0.94,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 130,
      },
      {
        level: 18,
        levelUpCostBlb: 152,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 9120,
        boostingCostBlb: 912,
        boostingCostLbl: 0,
        chargingCostBlb: 0.96,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 140,
      },
      {
        level: 19,
        levelUpCostBlb: 480,
        levelUpCostLbl: 480,
        levelUpRequiredMinutes: 9600,
        boostingCostBlb: 960,
        boostingCostLbl: 0,
        chargingCostBlb: 0.98,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 150,
      },
      {
        level: 20,
        levelUpCostBlb: 168,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 10080,
        boostingCostBlb: 1008,
        boostingCostLbl: 0,
        chargingCostBlb: 1,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 160,
      },
      {
        level: 21,
        levelUpCostBlb: 176,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 10560,
        boostingCostBlb: 1056,
        boostingCostLbl: 0,
        chargingCostBlb: 1.02,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 170,
      },
      {
        level: 22,
        levelUpCostBlb: 184,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 11040,
        boostingCostBlb: 1104,
        boostingCostLbl: 0,
        chargingCostBlb: 1.04,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 180,
      },
      {
        level: 23,
        levelUpCostBlb: 192,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 11520,
        boostingCostBlb: 1152,
        boostingCostLbl: 0,
        chargingCostBlb: 1.06,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 195,
      },
      {
        level: 24,
        levelUpCostBlb: 200,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 12000,
        boostingCostBlb: 1200,
        boostingCostLbl: 0,
        chargingCostBlb: 1.08,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 210,
      },
      {
        level: 25,
        levelUpCostBlb: 208,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 12480,
        boostingCostBlb: 1248,
        boostingCostLbl: 0,
        chargingCostBlb: 1.1,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 225,
      },
      {
        level: 26,
        levelUpCostBlb: 216,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 12960,
        boostingCostBlb: 1296,
        boostingCostLbl: 0,
        chargingCostBlb: 1.12,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 240,
      },
      {
        level: 27,
        levelUpCostBlb: 224,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 13440,
        boostingCostBlb: 1344,
        boostingCostLbl: 0,
        chargingCostBlb: 1.14,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 255,
      },
      {
        level: 28,
        levelUpCostBlb: 232,
        levelUpCostLbl: 232,
        levelUpRequiredMinutes: 13920,
        boostingCostBlb: 1392,
        boostingCostLbl: 0,
        chargingCostBlb: 1.16,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 270,
      },
      {
        level: 29,
        levelUpCostBlb: 800,
        levelUpCostLbl: 800,
        levelUpRequiredMinutes: 14400,
        boostingCostBlb: 1440,
        boostingCostLbl: 0,
        chargingCostBlb: 1.18,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 285,
      },
      {
        level: 30,
        levelUpCostBlb: 999999999,
        levelUpCostLbl: 999999999,
        levelUpRequiredMinutes: 999999999,
        boostingCostBlb: 999999999,
        boostingCostLbl: 999999999,
        chargingCostBlb: 1.2,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 300,
      },
    ],
  },
  {
    id: 4,
    formulaName: 'legendaryHeadphoneLevelAndCharge',
    description: 'legendaryHeadphoneLevelAndCharge',
    formulaArray: [
      {
        level: 0,
        levelUpCostBlb: 16,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 960,
        boostingCostBlb: 96,
        boostingCostLbl: 0,
        chargingCostBlb: 0.7,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 5,
      },
      {
        level: 1,
        levelUpCostBlb: 32,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 1920,
        boostingCostBlb: 192,
        boostingCostLbl: 0,
        chargingCostBlb: 0.72,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 10,
      },
      {
        level: 2,
        levelUpCostBlb: 48,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 2880,
        boostingCostBlb: 288,
        boostingCostLbl: 0,
        chargingCostBlb: 0.74,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 15,
      },
      {
        level: 3,
        levelUpCostBlb: 64,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 3840,
        boostingCostBlb: 384,
        boostingCostLbl: 0,
        chargingCostBlb: 0.76,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 20,
      },
      {
        level: 4,
        levelUpCostBlb: 160,
        levelUpCostLbl: 160,
        levelUpRequiredMinutes: 4800,
        boostingCostBlb: 480,
        boostingCostLbl: 0,
        chargingCostBlb: 0.78,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 25,
      },
      {
        level: 5,
        levelUpCostBlb: 96,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 5760,
        boostingCostBlb: 576,
        boostingCostLbl: 0,
        chargingCostBlb: 0.8,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 30,
      },
      {
        level: 6,
        levelUpCostBlb: 112,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 6720,
        boostingCostBlb: 672,
        boostingCostLbl: 0,
        chargingCostBlb: 0.82,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 35,
      },
      {
        level: 7,
        levelUpCostBlb: 128,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 7680,
        boostingCostBlb: 768,
        boostingCostLbl: 0,
        chargingCostBlb: 0.84,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 40,
      },
      {
        level: 8,
        levelUpCostBlb: 144,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 8640,
        boostingCostBlb: 864,
        boostingCostLbl: 0,
        chargingCostBlb: 0.86,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 45,
      },
      {
        level: 9,
        levelUpCostBlb: 480,
        levelUpCostLbl: 480,
        levelUpRequiredMinutes: 9600,
        boostingCostBlb: 960,
        boostingCostLbl: 0,
        chargingCostBlb: 0.88,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 50,
      },
      {
        level: 10,
        levelUpCostBlb: 176,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 10560,
        boostingCostBlb: 1056,
        boostingCostLbl: 0,
        chargingCostBlb: 0.9,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 60,
      },
      {
        level: 11,
        levelUpCostBlb: 192,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 11520,
        boostingCostBlb: 1152,
        boostingCostLbl: 0,
        chargingCostBlb: 0.92,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 70,
      },
      {
        level: 12,
        levelUpCostBlb: 208,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 12480,
        boostingCostBlb: 1248,
        boostingCostLbl: 0,
        chargingCostBlb: 0.94,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 80,
      },
      {
        level: 13,
        levelUpCostBlb: 224,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 13440,
        boostingCostBlb: 1344,
        boostingCostLbl: 0,
        chargingCostBlb: 0.96,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 90,
      },
      {
        level: 14,
        levelUpCostBlb: 240,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 14400,
        boostingCostBlb: 1440,
        boostingCostLbl: 0,
        chargingCostBlb: 0.98,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 100,
      },
      {
        level: 15,
        levelUpCostBlb: 256,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 15360,
        boostingCostBlb: 1536,
        boostingCostLbl: 0,
        chargingCostBlb: 1,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 110,
      },
      {
        level: 16,
        levelUpCostBlb: 272,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 16320,
        boostingCostBlb: 1632,
        boostingCostLbl: 0,
        chargingCostBlb: 1.02,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 120,
      },
      {
        level: 17,
        levelUpCostBlb: 288,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 17280,
        boostingCostBlb: 1728,
        boostingCostLbl: 0,
        chargingCostBlb: 1.04,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 130,
      },
      {
        level: 18,
        levelUpCostBlb: 304,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 18240,
        boostingCostBlb: 1824,
        boostingCostLbl: 0,
        chargingCostBlb: 1.06,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 140,
      },
      {
        level: 19,
        levelUpCostBlb: 960,
        levelUpCostLbl: 960,
        levelUpRequiredMinutes: 19200,
        boostingCostBlb: 1920,
        boostingCostLbl: 0,
        chargingCostBlb: 1.08,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 150,
      },
      {
        level: 20,
        levelUpCostBlb: 336,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 20160,
        boostingCostBlb: 2016,
        boostingCostLbl: 0,
        chargingCostBlb: 1.1,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 160,
      },
      {
        level: 21,
        levelUpCostBlb: 352,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 21120,
        boostingCostBlb: 2112,
        boostingCostLbl: 0,
        chargingCostBlb: 1.12,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 170,
      },
      {
        level: 22,
        levelUpCostBlb: 368,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 22080,
        boostingCostBlb: 2208,
        boostingCostLbl: 0,
        chargingCostBlb: 1.14,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 180,
      },
      {
        level: 23,
        levelUpCostBlb: 384,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 23040,
        boostingCostBlb: 2304,
        boostingCostLbl: 0,
        chargingCostBlb: 1.16,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 195,
      },
      {
        level: 24,
        levelUpCostBlb: 400,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 24000,
        boostingCostBlb: 2400,
        boostingCostLbl: 0,
        chargingCostBlb: 1.18,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 210,
      },
      {
        level: 25,
        levelUpCostBlb: 416,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 24960,
        boostingCostBlb: 2496,
        boostingCostLbl: 0,
        chargingCostBlb: 1.2,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 225,
      },
      {
        level: 26,
        levelUpCostBlb: 432,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 25920,
        boostingCostBlb: 2592,
        boostingCostLbl: 0,
        chargingCostBlb: 1.22,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 240,
      },
      {
        level: 27,
        levelUpCostBlb: 448,
        levelUpCostLbl: 0,
        levelUpRequiredMinutes: 26880,
        boostingCostBlb: 2688,
        boostingCostLbl: 0,
        chargingCostBlb: 1.24,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 255,
      },
      {
        level: 28,
        levelUpCostBlb: 464,
        levelUpCostLbl: 464,
        levelUpRequiredMinutes: 27840,
        boostingCostBlb: 2784,
        boostingCostLbl: 0,
        chargingCostBlb: 1.26,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 270,
      },
      {
        level: 29,
        levelUpCostBlb: 1600,
        levelUpCostLbl: 1600,
        levelUpRequiredMinutes: 28800,
        boostingCostBlb: 2880,
        boostingCostLbl: 0,
        chargingCostBlb: 1.28,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 285,
      },
      {
        level: 30,
        levelUpCostBlb: 999999999,
        levelUpCostLbl: 999999999,
        levelUpRequiredMinutes: 999999999,
        boostingCostBlb: 999999999,
        boostingCostLbl: 999999999,
        chargingCostBlb: 1.3,
        chargingCostLbl: 0,
        dailyTokenEarningLimit: 300,
      },
    ],
  },
  {
    id: 5,
    formulaName: 'stickerUpgrade',
    description: 'stickerUpgrade',
    formulaArray: [
      {
        level: 1,
        successRate: 0.35,
        levelUpCostBlb: 100,
        levelUpCostLbl: 10,
        requiredNumber: 3,
        additionalStatPoint: 2,
        percentToBaseAttribute: 0.05,
      },
      {
        level: 2,
        successRate: 0.55,
        levelUpCostBlb: 500,
        levelUpCostLbl: 50,
        requiredNumber: 3,
        additionalStatPoint: 8,
        percentToBaseAttribute: 0.7,
      },
      {
        level: 3,
        successRate: 0.65,
        levelUpCostBlb: 900,
        levelUpCostLbl: 90,
        requiredNumber: 3,
        additionalStatPoint: 25,
        percentToBaseAttribute: 2.2,
      },
      {
        level: 4,
        successRate: 0.75,
        levelUpCostBlb: 1300,
        levelUpCostLbl: 130,
        requiredNumber: 3,
        additionalStatPoint: 72,
        percentToBaseAttribute: 6,
      },
      {
        level: 5,
        successRate: 0.85,
        levelUpCostBlb: 1700,
        levelUpCostLbl: 170,
        requiredNumber: 3,
        additionalStatPoint: 200,
        percentToBaseAttribute: 12,
      },
      {
        level: 6,
        successRate: 1,
        levelUpCostBlb: 2100,
        levelUpCostLbl: 210,
        requiredNumber: 3,
        additionalStatPoint: 400,
        percentToBaseAttribute: 43,
      },
      {
        level: 7,
        successRate: 1,
        levelUpCostBlb: 2500,
        levelUpCostLbl: 250,
        requiredNumber: 3,
        additionalStatPoint: 600,
        percentToBaseAttribute: 74,
      },
      {
        level: 8,
        successRate: 1,
        levelUpCostBlb: 2900,
        levelUpCostLbl: 290,
        requiredNumber: 3,
        additionalStatPoint: 800,
        percentToBaseAttribute: 105,
      },
      {
        level: 9,
        successRate: 0,
        levelUpCostBlb: 999999999,
        levelUpCostLbl: 999999999,
        requiredNumber: 999999999,
        additionalStatPoint: 1000,
        percentToBaseAttribute: 136,
      },
    ],
  },
  {
    id: 6,
    formulaName: 'dockOpen',
    description: 'dockOpen',
    formulaArray: [
      {
        position: 1,
        headphoneQuality: 'COMMON',
        openCostBlb: 10,
        percentToAdditionalAttribute: 0,
      },
      {
        position: 1,
        headphoneQuality: 'UNCOMMON',
        openCostBlb: 20,
        percentToAdditionalAttribute: 0.1,
      },
      {
        position: 1,
        headphoneQuality: 'RARE',
        openCostBlb: 30,
        percentToAdditionalAttribute: 0.2,
      },
      {
        position: 1,
        headphoneQuality: 'EPIC',
        openCostBlb: 40,
        percentToAdditionalAttribute: 0.3,
      },
      {
        position: 1,
        headphoneQuality: 'LEGENDARY',
        openCostBlb: 50,
        percentToAdditionalAttribute: 0.5,
      },
      {
        position: 2,
        headphoneQuality: 'COMMON',
        openCostBlb: 10,
        percentToAdditionalAttribute: 0,
      },
      {
        position: 2,
        headphoneQuality: 'UNCOMMON',
        openCostBlb: 20,
        percentToAdditionalAttribute: 0.1,
      },
      {
        position: 2,
        headphoneQuality: 'RARE',
        openCostBlb: 30,
        percentToAdditionalAttribute: 0.2,
      },
      {
        position: 2,
        headphoneQuality: 'EPIC',
        openCostBlb: 40,
        percentToAdditionalAttribute: 0.3,
      },
      {
        position: 2,
        headphoneQuality: 'LEGENDARY',
        openCostBlb: 50,
        percentToAdditionalAttribute: 0.5,
      },
      {
        position: 3,
        headphoneQuality: 'COMMON',
        openCostBlb: 10,
        percentToAdditionalAttribute: 0,
      },
      {
        position: 3,
        headphoneQuality: 'UNCOMMON',
        openCostBlb: 20,
        percentToAdditionalAttribute: 0.1,
      },
      {
        position: 3,
        headphoneQuality: 'RARE',
        openCostBlb: 30,
        percentToAdditionalAttribute: 0.2,
      },
      {
        position: 3,
        headphoneQuality: 'EPIC',
        openCostBlb: 40,
        percentToAdditionalAttribute: 0.3,
      },
      {
        position: 3,
        headphoneQuality: 'LEGENDARY',
        openCostBlb: 50,
        percentToAdditionalAttribute: 0.5,
      },
      {
        position: 4,
        headphoneQuality: 'COMMON',
        openCostBlb: 10,
        percentToAdditionalAttribute: 0,
      },
      {
        position: 4,
        headphoneQuality: 'UNCOMMON',
        openCostBlb: 20,
        percentToAdditionalAttribute: 0.1,
      },
      {
        position: 4,
        headphoneQuality: 'RARE',
        openCostBlb: 30,
        percentToAdditionalAttribute: 0.2,
      },
      {
        position: 4,
        headphoneQuality: 'EPIC',
        openCostBlb: 40,
        percentToAdditionalAttribute: 0.3,
      },
      {
        position: 4,
        headphoneQuality: 'LEGENDARY',
        openCostBlb: 50,
        percentToAdditionalAttribute: 0.5,
      },
    ],
  },
  {
    id: 7,
    formulaName: 'mysteryBoxOpen',
    description: 'mysteryBoxOpen',
    formulaArray: [
      {
        quality: 'DAMAGED',
        openCostBlb: 5,
        openCostLbl: 0,
        boostingCostBlb: 9.3,
        boostingCostLbl: 0,
        openingRequiredMinutes: 2880,
      },
      {
        quality: 'REFURBISHED',
        openCostBlb: 7,
        openCostLbl: 0,
        boostingCostBlb: 21.6,
        boostingCostLbl: 0,
        openingRequiredMinutes: 4320,
      },
      {
        quality: 'COMMON',
        openCostBlb: 9,
        openCostLbl: 0,
        boostingCostBlb: 28.799999999999997,
        boostingCostLbl: 0,
        openingRequiredMinutes: 5760,
      },
      {
        quality: 'UNCOMMON',
        openCostBlb: 16,
        openCostLbl: 0,
        boostingCostBlb: 43.2,
        boostingCostLbl: 0,
        openingRequiredMinutes: 8640,
      },
      {
        quality: 'RARE',
        openCostBlb: 25,
        openCostLbl: 0,
        boostingCostBlb: 58,
        boostingCostLbl: 0,
        openingRequiredMinutes: 11520,
      },
      {
        quality: 'EPIC',
        openCostBlb: 36,
        openCostLbl: 0,
        boostingCostBlb: 72,
        boostingCostLbl: 0,
        openingRequiredMinutes: 14400,
      },
      {
        quality: 'LEGENDARY',
        openCostBlb: 49,
        openCostLbl: 0,
        boostingCostBlb: 86.4,
        boostingCostLbl: 0,
        openingRequiredMinutes: 17280,
      },
      {
        quality: 'ENCHANTED',
        openCostBlb: 64,
        openCostLbl: 0,
        boostingCostBlb: 100.8,
        boostingCostLbl: 0,
        openingRequiredMinutes: 20160,
      },
      {
        quality: 'MASTER',
        openCostBlb: 81,
        openCostLbl: 0,
        boostingCostBlb: 115.2,
        boostingCostLbl: 0,
        openingRequiredMinutes: 23040,
      },
      {
        quality: 'SATOSHI',
        openCostBlb: 100,
        openCostLbl: 0,
        boostingCostBlb: 129.6,
        boostingCostLbl: 0,
        openingRequiredMinutes: 25920,
      },
    ],
  },
  {
    id: 8,
    formulaName: 'mysteryBoxOpenItem',
    description: 'mysteryBoxOpenItem',
    formulaArray: [
      {
        blb: 0.5599999999999999,
        blbMax: 10,
        blbMin: 1,
        quality: 'DAMAGED',
        lvl1Sticker: 0.2,
        lvl2Sticker: 0.02,
        lvl3Sticker: 0,
        lvl4Sticker: 0,
        lvl5Sticker: 0,
        lvl6Sticker: 0,
        lvl7Sticker: 0,
        lvl8Sticker: 0,
        lvl9Sticker: 0,
        epicHeadphoneBox: 0,
        rareHeadphoneBox: 0,
        commonHeadphoneBox: 0.2,
        uncommonHeadphoneBox: 0.02,
        legendaryHeadphoneBox: 0,
      },
      {
        blb: 0.56,
        blbMax: 30,
        blbMin: 10,
        quality: 'REFURBISHED',
        lvl1Sticker: 0.1,
        lvl2Sticker: 0.07,
        lvl3Sticker: 0.05,
        lvl4Sticker: 0,
        lvl5Sticker: 0,
        lvl6Sticker: 0,
        lvl7Sticker: 0,
        lvl8Sticker: 0,
        lvl9Sticker: 0,
        epicHeadphoneBox: 0,
        rareHeadphoneBox: 0,
        commonHeadphoneBox: 0.15,
        uncommonHeadphoneBox: 0.07,
        legendaryHeadphoneBox: 0,
      },
      {
        blb: 0.5599999999999999,
        blbMax: 60,
        blbMin: 30,
        quality: 'COMMON',
        lvl1Sticker: 0,
        lvl2Sticker: 0.2,
        lvl3Sticker: 0.02,
        lvl4Sticker: 0,
        lvl5Sticker: 0,
        lvl6Sticker: 0,
        lvl7Sticker: 0,
        lvl8Sticker: 0,
        lvl9Sticker: 0,
        epicHeadphoneBox: 0,
        rareHeadphoneBox: 0,
        commonHeadphoneBox: 0.1,
        uncommonHeadphoneBox: 0.12,
        legendaryHeadphoneBox: 0,
      },
      {
        blb: 0.56,
        blbMax: 100,
        blbMin: 60,
        quality: 'UNCOMMON',
        lvl1Sticker: 0,
        lvl2Sticker: 0.1,
        lvl3Sticker: 0.07,
        lvl4Sticker: 0.05,
        lvl5Sticker: 0,
        lvl6Sticker: 0,
        lvl7Sticker: 0,
        lvl8Sticker: 0,
        lvl9Sticker: 0,
        epicHeadphoneBox: 0,
        rareHeadphoneBox: 0.02,
        commonHeadphoneBox: 0.05,
        uncommonHeadphoneBox: 0.15,
        legendaryHeadphoneBox: 0,
      },
      {
        blb: 0.54,
        blbMax: 200,
        blbMin: 100,
        quality: 'RARE',
        lvl1Sticker: 0,
        lvl2Sticker: 0.02,
        lvl3Sticker: 0.2,
        lvl4Sticker: 0.02,
        lvl5Sticker: 0,
        lvl6Sticker: 0,
        lvl7Sticker: 0,
        lvl8Sticker: 0,
        lvl9Sticker: 0,
        epicHeadphoneBox: 0,
        rareHeadphoneBox: 0.07,
        commonHeadphoneBox: 0,
        uncommonHeadphoneBox: 0.15,
        legendaryHeadphoneBox: 0,
      },
      {
        blb: 0.56,
        blbMax: 450,
        blbMin: 200,
        quality: 'EPIC',
        lvl1Sticker: 0,
        lvl2Sticker: 0,
        lvl3Sticker: 0.1,
        lvl4Sticker: 0.07,
        lvl5Sticker: 0.05,
        lvl6Sticker: 0,
        lvl7Sticker: 0,
        lvl8Sticker: 0,
        lvl9Sticker: 0,
        epicHeadphoneBox: 0,
        rareHeadphoneBox: 0.12,
        commonHeadphoneBox: 0,
        uncommonHeadphoneBox: 0.1,
        legendaryHeadphoneBox: 0,
      },
      {
        blb: 0.5599999999999999,
        blbMax: 800,
        blbMin: 450,
        quality: 'LEGENDARY',
        lvl1Sticker: 0,
        lvl2Sticker: 0,
        lvl3Sticker: 0,
        lvl4Sticker: 0.2,
        lvl5Sticker: 0.02,
        lvl6Sticker: 0,
        lvl7Sticker: 0,
        lvl8Sticker: 0,
        lvl9Sticker: 0,
        epicHeadphoneBox: 0.02,
        rareHeadphoneBox: 0.15,
        commonHeadphoneBox: 0,
        uncommonHeadphoneBox: 0.05,
        legendaryHeadphoneBox: 0,
      },
      {
        blb: 0.56,
        blbMax: 1700,
        blbMin: 800,
        quality: 'ENCHANTED',
        lvl1Sticker: 0,
        lvl2Sticker: 0,
        lvl3Sticker: 0,
        lvl4Sticker: 0.1,
        lvl5Sticker: 0.07,
        lvl6Sticker: 0.05,
        lvl7Sticker: 0,
        lvl8Sticker: 0,
        lvl9Sticker: 0,
        epicHeadphoneBox: 0.07,
        rareHeadphoneBox: 0.15,
        commonHeadphoneBox: 0,
        uncommonHeadphoneBox: 0,
        legendaryHeadphoneBox: 0,
      },
      {
        blb: 0.73,
        blbMax: 3500,
        blbMin: 1700,
        quality: 'MASTER',
        lvl1Sticker: 0,
        lvl2Sticker: 0,
        lvl3Sticker: 0,
        lvl4Sticker: 0,
        lvl5Sticker: 0,
        lvl6Sticker: 0.02,
        lvl7Sticker: 0.02,
        lvl8Sticker: 0.01,
        lvl9Sticker: 0,
        epicHeadphoneBox: 0.12,
        rareHeadphoneBox: 0.1,
        commonHeadphoneBox: 0,
        uncommonHeadphoneBox: 0,
        legendaryHeadphoneBox: 0,
      },
      {
        blb: 0.6299999999999999,
        blbMax: 7000,
        blbMin: 3500,
        quality: 'SATOSHI',
        lvl1Sticker: 0,
        lvl2Sticker: 0,
        lvl3Sticker: 0,
        lvl4Sticker: 0,
        lvl5Sticker: 0,
        lvl6Sticker: 0.07,
        lvl7Sticker: 0.05,
        lvl8Sticker: 0.02,
        lvl9Sticker: 0.01,
        epicHeadphoneBox: 0.15,
        rareHeadphoneBox: 0.05,
        commonHeadphoneBox: 0,
        uncommonHeadphoneBox: 0,
        legendaryHeadphoneBox: 0.02,
      },
    ],
  },
  {
    id: 9,
    formulaName: 'headphoneBoxQuality',
    description: 'headphoneBoxQuality',
    formulaArray: [
      {
        epicHeadphoneBox: 0,
        rareHeadphoneBox: 0,
        headphone1Quality: 'COMMON',
        headphone2Quality: 'COMMON',
        commonHeadphoneBox: 1,
        uncommonHeadphoneBox: 0,
        legendaryHeadphoneBox: 0,
      },
      {
        epicHeadphoneBox: 0,
        rareHeadphoneBox: 0.01,
        headphone1Quality: 'COMMON',
        headphone2Quality: 'UNCOMMON',
        commonHeadphoneBox: 0.5,
        uncommonHeadphoneBox: 0.49,
        legendaryHeadphoneBox: 0,
      },
      {
        epicHeadphoneBox: 0.01,
        rareHeadphoneBox: 0.49,
        headphone1Quality: 'COMMON',
        headphone2Quality: 'RARE',
        commonHeadphoneBox: 0.5,
        uncommonHeadphoneBox: 0,
        legendaryHeadphoneBox: 0,
      },
      {
        epicHeadphoneBox: 0.49,
        rareHeadphoneBox: 0,
        headphone1Quality: 'COMMON',
        headphone2Quality: 'EPIC',
        commonHeadphoneBox: 0.5,
        uncommonHeadphoneBox: 0,
        legendaryHeadphoneBox: 0.01,
      },
      {
        epicHeadphoneBox: 0,
        rareHeadphoneBox: 0,
        headphone1Quality: 'COMMON',
        headphone2Quality: 'LEGENDARY',
        commonHeadphoneBox: 0.5,
        uncommonHeadphoneBox: 0,
        legendaryHeadphoneBox: 0.5,
      },
      {
        epicHeadphoneBox: 0,
        rareHeadphoneBox: 0.02,
        headphone1Quality: 'UNCOMMON',
        headphone2Quality: 'UNCOMMON',
        commonHeadphoneBox: 0,
        uncommonHeadphoneBox: 0.98,
        legendaryHeadphoneBox: 0,
      },
      {
        epicHeadphoneBox: 0.01,
        rareHeadphoneBox: 0.5,
        headphone1Quality: 'UNCOMMON',
        headphone2Quality: 'RARE',
        commonHeadphoneBox: 0,
        uncommonHeadphoneBox: 0.49,
        legendaryHeadphoneBox: 0,
      },
      {
        epicHeadphoneBox: 0.49,
        rareHeadphoneBox: 0.01,
        headphone1Quality: 'UNCOMMON',
        headphone2Quality: 'EPIC',
        commonHeadphoneBox: 0,
        uncommonHeadphoneBox: 0.49,
        legendaryHeadphoneBox: 0.01,
      },
      {
        epicHeadphoneBox: 0,
        rareHeadphoneBox: 0.01,
        headphone1Quality: 'UNCOMMON',
        headphone2Quality: 'LEGENDARY',
        commonHeadphoneBox: 0,
        uncommonHeadphoneBox: 0.49,
        legendaryHeadphoneBox: 0.5,
      },
      {
        epicHeadphoneBox: 0.02,
        rareHeadphoneBox: 0.98,
        headphone1Quality: 'RARE',
        headphone2Quality: 'RARE',
        commonHeadphoneBox: 0,
        uncommonHeadphoneBox: 0,
        legendaryHeadphoneBox: 0,
      },
      {
        epicHeadphoneBox: 0.5,
        rareHeadphoneBox: 0.49,
        headphone1Quality: 'RARE',
        headphone2Quality: 'EPIC',
        commonHeadphoneBox: 0,
        uncommonHeadphoneBox: 0,
        legendaryHeadphoneBox: 0.01,
      },
      {
        epicHeadphoneBox: 0.01,
        rareHeadphoneBox: 0.49,
        headphone1Quality: 'RARE',
        headphone2Quality: 'LEGENDARY',
        commonHeadphoneBox: 0,
        uncommonHeadphoneBox: 0,
        legendaryHeadphoneBox: 0.5,
      },
      {
        epicHeadphoneBox: 0.98,
        rareHeadphoneBox: 0,
        headphone1Quality: 'EPIC',
        headphone2Quality: 'EPIC',
        commonHeadphoneBox: 0,
        uncommonHeadphoneBox: 0,
        legendaryHeadphoneBox: 0.02,
      },
      {
        epicHeadphoneBox: 0.49,
        rareHeadphoneBox: 0,
        headphone1Quality: 'EPIC',
        headphone2Quality: 'LEGENDARY',
        commonHeadphoneBox: 0,
        uncommonHeadphoneBox: 0,
        legendaryHeadphoneBox: 0.51,
      },
      {
        epicHeadphoneBox: 0,
        rareHeadphoneBox: 0,
        headphone1Quality: 'LEGENDARY',
        headphone2Quality: 'LEGENDARY',
        commonHeadphoneBox: 0,
        uncommonHeadphoneBox: 0,
        legendaryHeadphoneBox: 1,
      },
    ],
  },
  {
    id: 10,
    formulaName: 'headphoneBoxDockAttibute',
    description: 'headphoneBoxDockAttibute',
    formulaArray: [
      {
        luck: 0.1,
        comfort: 0.1,
        efficiency: 0.7,
        resilience: 0.1,
        headphone1Attribute: 'EFFICIENCY',
        headphone2Attribute: 'EFFICIENCY',
      },
      {
        luck: 0.4,
        comfort: 0.1,
        efficiency: 0.4,
        resilience: 0.1,
        headphone1Attribute: 'EFFICIENCY',
        headphone2Attribute: 'LUCK',
      },
      {
        luck: 0.1,
        comfort: 0.4,
        efficiency: 0.4,
        resilience: 0.1,
        headphone1Attribute: 'EFFICIENCY',
        headphone2Attribute: 'RESILIENCE',
      },
      {
        luck: 0.1,
        comfort: 0.4,
        efficiency: 0.4,
        resilience: 0.1,
        headphone1Attribute: 'EFFICIENCY',
        headphone2Attribute: 'COMFORT',
      },
      {
        luck: 0.7,
        comfort: 0.1,
        efficiency: 0.1,
        resilience: 0.1,
        headphone1Attribute: 'LUCK',
        headphone2Attribute: 'LUCK',
      },
      {
        luck: 0.4,
        comfort: 0.1,
        efficiency: 0.1,
        resilience: 0.4,
        headphone1Attribute: 'LUCK',
        headphone2Attribute: 'RESILIENCE',
      },
      {
        luck: 0.4,
        comfort: 0.4,
        efficiency: 0.1,
        resilience: 0.1,
        headphone1Attribute: 'LUCK',
        headphone2Attribute: 'COMFORT',
      },
      {
        luck: 0.1,
        comfort: 0.1,
        efficiency: 0.1,
        resilience: 0.7,
        headphone1Attribute: 'RESILIENCE',
        headphone2Attribute: 'RESILIENCE',
      },
      {
        luck: 0.1,
        comfort: 0.4,
        efficiency: 0.1,
        resilience: 0.4,
        headphone1Attribute: 'RESILIENCE',
        headphone2Attribute: 'COMFORT',
      },
      {
        luck: 0.1,
        comfort: 0.7,
        efficiency: 0.1,
        resilience: 0.1,
        headphone1Attribute: 'COMFORT',
        headphone2Attribute: 'COMFORT',
      },
    ],
  },
  {
    id: 11,
    formulaName: 'headphoneQualityFromBox',
    description: 'headphoneQualityFromBox',
    formulaArray: [
      {
        statMax: 10,
        statMin: 1,
        epicHeadphone: 0,
        rareHeadphone: 0,
        commonHeadphone: 0.97,
        uncommonHeadphone: 0.03,
        legendaryHeadphone: 0,
        headphoneBoxQuality: 'COMMON',
      },
      {
        statMax: 18,
        statMin: 8,
        epicHeadphone: 0,
        rareHeadphone: 0.02,
        commonHeadphone: 0.25,
        uncommonHeadphone: 0.73,
        legendaryHeadphone: 0,
        headphoneBoxQuality: 'UNCOMMON',
      },
      {
        statMax: 35,
        statMin: 15,
        epicHeadphone: 0.02,
        rareHeadphone: 0.71,
        commonHeadphone: 0,
        uncommonHeadphone: 0.27,
        legendaryHeadphone: 0,
        headphoneBoxQuality: 'RARE',
      },
      {
        statMax: 63,
        statMin: 28,
        epicHeadphone: 0.68,
        rareHeadphone: 0.3,
        commonHeadphone: 0,
        uncommonHeadphone: 0,
        legendaryHeadphone: 0.02,
        headphoneBoxQuality: 'EPIC',
      },
      {
        statMax: 112,
        statMin: 50,
        epicHeadphone: 0.35,
        rareHeadphone: 0,
        commonHeadphone: 0,
        uncommonHeadphone: 0,
        legendaryHeadphone: 0.65,
        headphoneBoxQuality: 'LEGENDARY',
      },
    ],
  },
  {
    id: 12,
    formulaName: 'headphoneBoxDockQuality',
    description: 'headphoneBoxDockQuality',
    formulaArray: [
      {
        headphoneQuality: 'COMMON',
        commonDockQuality: 0.9,
        uncommonDockQuality: 0.1,
        rareDockQuality: 0,
        epicDockQuality: 0,
        legendaryDockQuality: 0,
      },
      {
        headphoneQuality: 'UNCOMMON',
        commonDockQuality: 0.3,
        uncommonDockQuality: 0.6,
        rareDockQuality: 0.1,
        epicDockQuality: 0,
        legendaryDockQuality: 0,
      },
      {
        headphoneQuality: 'RARE',
        commonDockQuality: 0.1,
        uncommonDockQuality: 0.3,
        rareDockQuality: 0.5,
        epicDockQuality: 0.1,
        legendaryDockQuality: 0,
      },
      {
        headphoneQuality: 'EPIC',
        commonDockQuality: 0.1,
        uncommonDockQuality: 0.1,
        rareDockQuality: 0.3,
        epicDockQuality: 0.4,
        legendaryDockQuality: 0.1,
      },
      {
        headphoneQuality: 'LEGENDARY',
        commonDockQuality: 0,
        uncommonDockQuality: 0.1,
        rareDockQuality: 0.2,
        epicDockQuality: 0.3,
        legendaryDockQuality: 0.4,
      },
    ],
  },
  {
    id: 13,
    formulaName: 'mysteryBoxCreate',
    description: 'mysteryBoxCreate',
    formulaArray: [
      {
        epic: 0,
        rare: 0,
        common: 0.01,
        master: 0,
        damaged: 0.95,
        satoshi: 0,
        uncommon: 0,
        enchanted: 0,
        legendary: 0,
        refurbished: 0.04,
        qualityValueMax: 4,
        qualityValueMin: 1,
      },
      {
        epic: 0,
        rare: 0,
        common: 0.1,
        master: 0,
        damaged: 0.05,
        satoshi: 0,
        uncommon: 0.05,
        enchanted: 0,
        legendary: 0,
        refurbished: 0.8,
        qualityValueMax: 8,
        qualityValueMin: 5,
      },
      {
        epic: 0.04,
        rare: 0.05,
        common: 0.7,
        master: 0,
        damaged: 0.01,
        satoshi: 0,
        uncommon: 0.1,
        enchanted: 0,
        legendary: 0,
        refurbished: 0.1,
        qualityValueMax: 24,
        qualityValueMin: 9,
      },
      {
        epic: 0.1,
        rare: 0.15,
        common: 0.14,
        master: 0,
        damaged: 0,
        satoshi: 0,
        uncommon: 0.6,
        enchanted: 0,
        legendary: 0,
        refurbished: 0.01,
        qualityValueMax: 53,
        qualityValueMin: 25,
      },
      {
        epic: 0.15,
        rare: 0.6,
        common: 0.01,
        master: 0,
        damaged: 0,
        satoshi: 0,
        uncommon: 0.14,
        enchanted: 0,
        legendary: 0.1,
        refurbished: 0,
        qualityValueMax: 92,
        qualityValueMin: 54,
      },
      {
        epic: 0.6,
        rare: 0.14,
        common: 0,
        master: 0,
        damaged: 0,
        satoshi: 0,
        uncommon: 0.01,
        enchanted: 0.1,
        legendary: 0.15,
        refurbished: 0,
        qualityValueMax: 145,
        qualityValueMin: 93,
      },
      {
        epic: 0.14,
        rare: 0.01,
        common: 0,
        master: 0.1,
        damaged: 0,
        satoshi: 0,
        uncommon: 0,
        enchanted: 0.15,
        legendary: 0.6,
        refurbished: 0,
        qualityValueMax: 208,
        qualityValueMin: 146,
      },
      {
        epic: 0.01,
        rare: 0,
        common: 0,
        master: 0.15,
        damaged: 0,
        satoshi: 0.1,
        uncommon: 0,
        enchanted: 0.6,
        legendary: 0.14,
        refurbished: 0,
        qualityValueMax: 284,
        qualityValueMin: 209,
      },
      {
        epic: 0,
        rare: 0,
        common: 0,
        master: 0.6,
        damaged: 0,
        satoshi: 0.15,
        uncommon: 0,
        enchanted: 0.14,
        legendary: 0.11,
        refurbished: 0,
        qualityValueMax: 374,
        qualityValueMin: 285,
      },
      {
        epic: 0,
        rare: 0,
        common: 0,
        master: 0.1,
        damaged: 0,
        satoshi: 0.7,
        uncommon: 0,
        enchanted: 0.1,
        legendary: 0.1,
        refurbished: 0,
        qualityValueMax: 9999,
        qualityValueMin: 375,
      },
    ],
  },
  {
    id: 14,
    formulaName: 'headphoneAvailableMintCountByQuality',
    description: 'headphoneAvailableMintCountByQuality',
    formulaArray: [
      {
        headphoneQuality: 'COMMON',
        oneAvailableMint: 0,
        sixAvailableMint: 0.01,
        twoAvailableMint: 0,
        fiveAvailableMint: 0.01,
        fourAvailableMint: 0.01,
        zeroAvailableMint: 0,
        sevenAvailableMint: 0.97,
        threeAvailableMint: 0,
      },
      {
        headphoneQuality: 'UNCOMMON',
        oneAvailableMint: 0,
        sixAvailableMint: 0.3,
        twoAvailableMint: 0,
        fiveAvailableMint: 0.05,
        fourAvailableMint: 0.04,
        zeroAvailableMint: 0,
        sevenAvailableMint: 0.6,
        threeAvailableMint: 0.01,
      },
      {
        headphoneQuality: 'RARE',
        oneAvailableMint: 0,
        sixAvailableMint: 0.6,
        twoAvailableMint: 0.01,
        fiveAvailableMint: 0.15,
        fourAvailableMint: 0.05,
        zeroAvailableMint: 0,
        sevenAvailableMint: 0.15,
        threeAvailableMint: 0.04,
      },
      {
        headphoneQuality: 'EPIC',
        oneAvailableMint: 0.6,
        sixAvailableMint: 0,
        twoAvailableMint: 0.15,
        fiveAvailableMint: 0.02,
        fourAvailableMint: 0.03,
        zeroAvailableMint: 0.15,
        sevenAvailableMint: 0,
        threeAvailableMint: 0.05,
      },
      {
        headphoneQuality: 'LEGENDARY',
        oneAvailableMint: 0.3,
        sixAvailableMint: 0,
        twoAvailableMint: 0.05,
        fiveAvailableMint: 0,
        fourAvailableMint: 0.02,
        zeroAvailableMint: 0.6,
        sevenAvailableMint: 0,
        threeAvailableMint: 0.03,
      },
    ],
  },
];
