export const CONFIG_BASE_CRAWLER_OPTIONS = 'CONFIG_BASE_CRAWLER_OPTIONS';

export const DEPOSIT_TOKEN_EVENT = 'LogLockToken';

export const DEPOSIT_NFT_EVENT = 'LogLockNft';

export const TIME_STEP_CRAWL_IN_MILLISECONDS = 60000;
